### ISSUE TITLE
How to run clustermap.js?

### ISSUE THREAD

**Issue by zhangws119** [gamcil/clustermap.js#2]
Hi, 

Congratulation! I read the paper on bioRxiv, but it is a little bit hard for me to run clustermap.js. I have no experience with D3 and .js. How to run it on ubuntu or other platfortms. Actually, I do not know how to enter command line. Do I need to copy the code to run or enter some command like "./clustermap.js"? Could you help me to solve that or give me some suggests?

Thank you very much.

**Comment by gamcil** [comment]
Hey,

I think you might be looking for clinker (https://github.com/gamcil/clinker) - this is just the JavaScript code for the visualization that clinker uses internally. To use clinker, make sure Python is installed, and then in the command line:

`pip install clinker`

To run clinker, you can then do:

`clinker file1.gbk file2.gbk file3.gbk -p`
